export const Logos = [
    {
        id:1,
        src:"../images/logos/university-of-north-texas-unt-logo.png",
        link:"",
    },
    {
        id:2,
        src:"../images/logos/university-of-huddersfield.png",
        link:"",
    },
    {
        id:3,
        src:"../images/logos/yewon.png",
        link:"",

    },
    {
        id:4,
        src:"../images/logos/cleverinsight.png",
        link:"",
    },
    {
        id:5,
        src:"../images/logos/ficci.png",
        link:"",
    },
    {
        id:6,
        src:"../images/logos/feng-chia-university.png",
        link:"",
    },
    {
        id:7,
        
        src:"../images/logos/resense.png",
        link:"",
    },
    {
        id:8,
        src:"../images/logos/Binghamton.png",
        link:"",
    },
    {
        id:9,
       
        src:"../images/logos/kist.png",
        link:"",
    },
    {
        id:10,
        src:"../images/logos/ieee-usa.png",
        link:"",
    },
    {
        id:11,
        
        src:"../images/logos/triumf.png",
        link:"",
    },
    {
        id:12,
        src:"../images/logos/harvard.png",
        link:"",
    },
    {
        id:13,
        src:"../images/logos/makonis.png",
        link:"",
    },
    {
        id:14,
        src:"../images/logos/rimoce.png",
        link:"",
    },
    {
        id:15,
        src:"../images/logos/tus.png",
        link:"",
    },
    {
        id:16,
        src:"../images/logos/giz.png",
        link:"",
    },
    {
        id:17,
        src:"../images/logos/jbu.png",
        link:"",
    },
    {
        id:18,
        src:"../images/logos/brookhaven.png",
        link:"",
    },
    {
        id:19,
        src:"../images/logos/university-of-arkansas-at-little-rock.png",
        link:"",
    },
    {
        id:20,
        src:"../images/logos/amsterdam.png",
        link:"",
    },
    {
        id:21,
        src:"../images/logos/rwthu.png",
        link:"",
    },
]